PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX wep: <http://ns.inria.fr/meteo/ontology/property/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX weo: <http://ns.inria.fr/meteo/ontology/>

select ?jour ((avg(?v) - 273.15) as ?avgwsinCelsius)  where {
  ?obs a  <http://ns.inria.fr/meteo/ontology/MeteorologicalObservation>; 
sosa:observedProperty
              <http://ns.inria.fr/meteo/ontology/weatherproperty/airTemperature> ;
sosa:hasResult [ qudt:numericValue ?v]; 
wep:madeByStation ?station ;
sosa:resultTime ?t .
?station rdfs:label ?n ;  weo:stationID ?stationID
FILTER (?stationID = "07690" && month(?t) = 8)
BIND (day(?t) AS ?jour) 
} GROUP BY ?jour
