#lists weather properties labels, abbreviations and their possible units 
prefix qudt: <http://qudt.org/schema/qudt/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix weo: <http://ns.inria.fr/meteo/ontology/> 
select * where {
  ?x a weo:WeatherProperty
  ?x skos:PrefLabel ?l
  OPTIONAL {?x qudt:applicableUnit ?u}
}