PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX weo: <http://ns.inria.fr/meteo/ontology/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX wep: <http://ns.inria.fr/meteo/ontology/property/>
PREFIX qudt: <http://qudt.org/schema/qudt/>


select ?stationID  ?n ((avg(?v)- 273.15) as ?avgws)   where {
  ?obs a  <http://ns.inria.fr/meteo/ontology/MeteorologicalObservation>; 
sosa:observedProperty
              <http://ns.inria.fr/meteo/vocab/weatherproperty/airTemperature> ;
sosa:hasResult [ qudt:numericValue ?v]; 
wep:madeByStation ?station ;
sosa:resultTime ?t .
FILTER (day(?t) = 27 && month(?t) =8)
?station rdfs:label ?n ; weo:stationID ?stationID
}
GROUP BY ?stationID ?n
ORDER BY ?avgws
