PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select * where {
  ?x  qudt:applicableUnit  ?y.
  ?x rdfs:label ?l .
  ?x <http://ns.inria.fr/meteo/ontology/property/hasAbbreviation> ?a .
}

